import * as THREE from 'three';
export const START_FROM = 'DEGREES';
export const START_YAW_DEG = 125;
export const START_PITCH_DEG = 30;
export const START_POS = new THREE.Vector3(140, 10, -100);
export const LOOK_AT = new THREE.Vector3(100, 8, -140);
export const EYE_HEIGHT = 10.0;
export const MOVE_SPEED = 30;
export const RUN_MULTIPLIER = 2;
export const MAX_DT = 0.05;
export const INTERACT_MAX_DIST = 100;
export const HOVER_COLOR = new THREE.Color('#f59e0b');
export const HOVER_EMISSIVE_INTENSITY = 1.2;
export const LAMP_COLOR_ON = new THREE.Color('#4ade80');
export const LAMP_EMISSIVE_INTENSITY = 1.6;
export const WORLD_URL = '/models/bundkort3.gltf';
export const NAV_URL = '/models/nav1.gltf';
